### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by bumhooLIM** [ysBach/ysphotutilpy#2]
When I tried to import this packaged, following 'import error' occured.

**import** *ysphotuilpy* **as** *ypu*
----> 1 **from** .aperture **import** *
----> 8 **from** photutils.aperture.attributes **import** (AngleOrPixelScalarQuantity, ...) 

**ImportError**: cannot import name 'AngleOrPixelScalarQuantity' from 'photutils.aperture.attributes' (C:\Users\bumho\anaconda3\lib\site-packages\photutils\aperture\attributes.py)

Is this an issue with the update version of *photutils*?

**Comment by ysBach** [comment]
Thanks for reporting. 

Oh I think ``photutils`` made a backward incompatible change to its code... See https://github.com/astropy/photutils/commit/d61630e2ab835113db93f28f6fd427790329090e. 
I think I need to update the source code.
Until then, you may have to use photutils 1.3, not 1.4

**Comment by bumhooLIM** [comment]
Thanks for replying. Then I'll use the earlier version of `photutils`.

+) it works well when I tried with version 1.3.0

**Comment by hbahk** [comment]
How do you think splitting this master branch for a version compatible with `photutils<1.4` and editing the aperture.py with those new names?

```
from photutils.aperture.attributes import (ScalarAngleOrPixel,
                                           ScalarAngle, PixelPositions,
                                           PositiveScalar, ScalarAngleOrValue,
                                           SkyCoordPositions)
```

Is there any better way to control versions of `photutils`?
For me, it seems very ugly to import those classes with conditional statements.

**Comment by ysBach** [comment]
@hbahk Thanks for reminding this issue (also thanks to @bumhoo7 for opening this).
I made the following quick patch: https://github.com/ysBach/ysphotutilpy/commit/567fd47b1b55a047518c3b139b597f6ccf93e6c3

Actually, ``ScalarAngleOrPixel`` is used only for pill-box apertures that are not used in AO classes, so anyways it won't affect the AO class materials, hopefully---I made it and used it in [Ishiguro M., Bach, Y. P., et al. 2022, MNRAS](https://ui.adsabs.harvard.edu/abs/2022MNRAS.509.4128I/abstract).

Please feel free to re-open this issue if the problem persists.

**Comment by hbahk** [comment]
Thank you for the quick fix! But I believe `Scalar` should also be changed by `ScalarAngleOrValue` because of https://github.com/astropy/photutils/commit/a23de9fdaf442b5e34ae44c97f0c71636b33123f and https://github.com/astropy/photutils/commit/7e698ce756ff80d28fb6ed5bc9b6c2a0bf01cb55.

Thank you again for your dedicated work!

**Comment by ysBach** [comment]
@hbahk Ah, it was my bad (I tested the updated code with photutils 1.3, not 1.4).

I now find they changed too many parts in the internal API... Completely backward-incompatible changes.
I think it's almost impossible to update the aperture module to compatible with photutils 1.4.0 at this moment and I may need some more time.. Let me leave this issue be opened for a while.

**Comment by hbahk** [comment]
@ysBach Oh I didn't know. Thanks for the quick reply and sorry for bothering you 3:30 in the morning...
