### ISSUE TITLE
`'icrs' * u.deg` brings ValueError in queryutil.PanSTARRS1

### ISSUE THREAD

**Issue by hbahk** [ysBach/ysphotutilpy#3]
Hello, I found in c003e0688dd5414a54bc74d10779b45c654d439c, `'icrs'` was added as the default frame, but this brings error.

At line 642, `_params[k] = v * u.deg`, `v` becomes `'ircs'` for `'frame'` keyword, which gives rise to ValueError when this is multiplied by u.deg.

Plus I think you also wanted to change line 665 by `frame=self.frame`, but I'm not sure.

+ I append the error message too.

ValueError: 'icrs' did not parse as unit: At col 0, icrs is not a valid unit.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html

**Comment by ysBach** [comment]
@hbahk Hi and thank you very much for reporting this issue!
Could you provide a minimal example code to reproduce the error?

```python
import ysphotutilpy as ypu
# <code to reproduce the error>
```

**Comment by hbahk** [comment]
@ysBach 
This would be a minimal code to reproduce this.
```
import ysphotutilpy as ypu

q = ypu.PanSTARRS1(ra=130, dec=20, radius=0.01)
```
Thank you!

**Comment by ysBach** [comment]
@hbahk Oh, that was a stupid mistake, and I feel unittest is indeed necessary for my packages too....

@hbahk and ping to @bumhoo7 
For your information, Since this commit (https://github.com/ysBach/ysphotutilpy/commit/a3222a51d16c5f87d3e68cc4b49478fdbc995d09), ``ysphotutilpy`` will support ``photutils >= 1.4``. 

``photutils <= 1.3`` will fail to import this package.

**Comment by hbahk** [comment]
@ysBach Oh now it works well! Thank you for the compatibility update too!

**Comment by hbahk** [comment]
@ysBach And please look at the last line of below (it's from `PanSTARRS1.query`)

```
    def query(self):
        vquery = Vizier(columns=self.columns, column_filters=self.column_filters, row_limit=-1)

        field = SkyCoord(ra=self.ra, dec=self.dec, frame='icrs')
```

and consider changing it by `field = SkyCoord(ra=self.ra, dec=self.dec, frame=self.frame)` because otherwise the whole 'adding option to users' will be pointless...

Thank you again! Have a good day.

**Comment by ysBach** [comment]
@hbahk Ah, you're definitely right. Sorry I didn't update that part. Will push soon.
