### ISSUE TITLE
Same sky value for all apertures for `apphot.apphot_annulus`

### ISSUE THREAD

**Issue by hbahk** [ysBach/ysphotutilpy#4]
Hi, how are you?

There were questions about why result of the photometry using `apphot.apphot_annulus` have some negative source_sum values,  when we put multiple apertures in this function.
I found that the model sky value of the first aperture is applied for all other apertures to obtain source_sum.
I wonder why you adopted only one sky value, if this is not a mistake.

https://github.com/ysBach/ysphotutilpy/blob/65f43c234d34426d58d75ad1807a45ec9edc8741/ysphotutilpy/apphot.py#L242
https://github.com/ysBach/ysphotutilpy/blob/65f43c234d34426d58d75ad1807a45ec9edc8741/ysphotutilpy/apphot.py#L257-L263

Thank you as always for your help.

**Comment by ysBach** [comment]
Thank you very much for reporting this issue.
I think it is a critical bug...
My bad I did not make proper unittests..

Could you please try the new commit?
Sorry for the inconvenience...

**Comment by hbahk** [comment]
It works well! Thank you so much!!!
